defaults: &defaults
  working_directory: ~/app
  docker:
    - image: node:10

version: 2
jobs:

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "package.json" }}
      - run: yarn
      # - run:
      #     name: Audit NPM Packages
      #     command: yarn audit
      - save_cache:
          key: v1-{{ checksum "package.json" }}
          paths:
            - node_modules


workflows:
  version: 2

  general:
    jobs:
      - test
